### ISSUE TITLE
Doesn't work with OrderBy

### ISSUE THREAD

**Issue by MateiC** [mmnaseri/spring-data-mock#175]
**Describe the bug**
Hey,

While trying out the library, it bugged out when I tried to use it in our project on a JPA method using the OrderBy.

**To Reproduce**
Create a OrderBy method
Run tests

**Expected behavior**
No compile issues...

[SpringDataMockBug.txt](https://github.com/mmnaseri/spring-data-mock/files/5458591/SpringDataMockBug.txt)

**Comment by mmnaseri** [comment]
You have uncovered a real issue here, that the framework does not support `find` with only a sort specified and no query parameters added.  However, your usage is also incorrect: your method name is `findAllOrderByBlablaAsc`, whereas it should be `findAllByOrderByBlablaAsc`. See https://stackoverflow.com/a/27427359 for more info.

**Comment by mmnaseri** [comment]
I've merged a fix into `development` and will prepare a release (2.1.1) with the fix attached soon.

**Comment by MateiC** [comment]
Hello,

Thank you! Indeed the query was wrong :D I saw it in our legacy code and
thought it was weird so I modified it but didn't test it.

Thanks for the fix!

Best regards,
Matei
