### ISSUE TITLE
Error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by daschy** [mmnaseri/spring-data-mock#2]
Hi, 

I am getting this error when I try to save the User entities in the mocked repository. I cannot use DBUnit, since I need to test entities with dynamic data (ex: lastSeen timestamp), so spring-data-mock is perfect for my use case.

Here the error.

https://i.imgur.com/AYzPWLl.png

 `User u = new User();
u.setName("admin");
u.setFirstName("admin");
u.setEmail("test@example.org");
u.lastSeen(new Date().getTime());

UserRepository repo = RepositoryMock
                .forRepository(UserRepository.class,"id", KeyGeneration.NONE)
                .mock();
        repo.save(u);`

The User class extends the AbstractEntity, where the ID (readonly) is generated. UserRepository contains methods with @Query annotations as well.

My tech stack is Spring-Data on top of Hibernate, Jackson and Lombok. 

Do you have any clou why this error is generated, or in what direction I need looking into?

Thanks

M.

**Comment by mmnaseri** [comment]
Hi. Thanks for opening the issue. I have a hunch that this comes from the ID being readonly, since upon saving, the repository will attempt to set the ID via the setter.

I am actively working on a new version of this project. It is a %100 rewrite with better functionality support and better conformance to the Spring standards.

You can check it out under the branch `dev` and see if that works for you. Under the new code base, what you have here would be written using:

    UserRepository repo = RepositoryFactoryBuilder.builder().mock(UserRepository.class);

**Comment by mmnaseri** [comment]
I have a test case under the `dev` branch at `com.mmnaseri.utils.spring.data.domain.impl.CustomEntityTest` outlining the scenario you have described here. Please confirm if that adheres to your specification.

**Comment by mmnaseri** [comment]
Since the issue seems to be resolved in the newer version, I will mark this as `invalid` and close it with fixed.
